### ISSUE TITLE
Sub items not displaying in autonav

### ISSUE THREAD

**Issue by foiseworth** [jordanlev/c5_clean_block_templates#3]
Sub items are being displayed when logged in but not logged out. I have switched to the base c5 template and all items are displayed fine. I think the issue is with this code:

``` php
foreach ($allNavItems as $ni) {
    $_c = $ni->getCollectionObject();
    $current_level = $ni->getLevel();

    if ($_c->getAttribute('exclude_nav') && ($current_level <= $excluded_parent_level)) {
        $excluded_parent_level = $current_level;
        $exclude_page = true;
    } else if (($current_level > $excluded_parent_level) || ($current_level > $exclude_children_below_level)) {
        $exclude_page = true;
    } else {
        $excluded_parent_level = 9999; //Reset to arbitrarily high number to denote that we're no longer excluding a parent
        $exclude_children_below_level = $_c->getAttribute('exclude_subpages_from_nav') ? $current_level : 9999;
        $exclude_page = false;
    }

    if (!$exclude_page) {
        $includedNavItems[] = $ni;
    }
}
```

because if I add $exclude_page = false; just before the end if statement all pages are displayed. I'll investigate further... apologies if it is an error on my part.

**Comment by jordanlev** [comment]
Thanks for reporting this. I suspect what is happening is that one of the parent pages has permissions set which hide it from guests (non-logged-in viewers). Try checking the permissions on the page that is just above the sub-pages which aren't showing up when logged out.

**Comment by foiseworth** [comment]
Hi jordanlev,

Thanks for the speedy reply! I have double checked and there are no permissions set. This happens for every first level item (7) with sub items. It doesn't happen with the default nav either so surely that would rule out permissions?

Many thanks for your assistance,

foiseworth

**Comment by jordanlev** [comment]
Hmm... can you send me an admin login to your site (email me directly at concrete@jordanlev.com)? Also, please attach the full custom template file you're using (the one that is not displaying the sub-pages properly).

**Comment by foiseworth** [comment]
Hi Jordanlev,

Apologies for the delay in replying. This issues seems to have mysteriously vanished and I cannot get it to reproduce....
