### ISSUE TITLE
Autonav template and dropdown menu

### ISSUE THREAD

**Issue by sciascia** [jordanlev/c5_clean_block_templates#5]
Hey There Jordan,

I'm sorry to bug you but I'm having trouble creating a dropdown menu (I'm trying to avoid mixing php and HTML and follow these rules: http://getkirby.com/blog/php-templates) but am having trouble understanding how to output each level properly. 

What I have outputs every page on the site, then every page again within each dropdown.

If you have any time, some pointers in the right direction would be much appreciated. 

``` php
<ul class="main-nav-left">
<? foreach($navItems as $ni) : ?>
  <li class="dropdown <?= ($ni->classes) ? $ni->classes : '' ?>">

  <? if ($ni->isEnabled) : ?>
    <a class="dropdown-toggle <?= $ni->classes ?>" href="<?= $ni->url ?>"><?= $ni->name ?></a>
  <? else : ?>
    <span class="<?= $ni->classes ?>"><?= $ni->name ?></span>
  <? endif ?>

  <? if ($ni->hasSubmenu) : ?>
    <ul class="dropdown-menu">
    <? foreach($navItems as $ni) : ?>
      <li class="<?= $ni->classes ?>"><a href="<?= $ni->url ?>"><?= $ni->name ?></a></li>
    <? endforeach ?>
    </ul>
  <? endif ?>
  </li>
<? endforeach ?>
</ul>
```

Cheers

Ben

**Comment by sciascia** [comment]
Went with this in the end, not sure if it's the best way though...

``` php
<ul class="main-nav-left">
<? foreach($navItems as $ni) : ?>

  <? if ($ni->hasSubmenu) : ?>
    <li class="<?= $ni->classes ?> <?= str_replace(' ', '', strtolower($ni->name)); ?>">
    <? if ($ni->isEnabled) : ?>
      <a class="<?= $ni->classes ?> dropdown-toggle" href="<?= $ni->url ?>"><?= $ni->name ?></a>
    <? else : ?>
      <span class="<?= $ni->classes ?>"><?= $ni->name ?></span>
    <? endif ?>
    <ul class="dropdown-menu">

  <? else : ?>
    <li class="<?= ($ni->classes) ?> <?= str_replace(' ', '', strtolower($ni->name)); ?>">
    <? if ($ni->isEnabled) : ?>
      <a class="<?= $ni->classes ?>" href="<?= $ni->url ?>"><?= $ni->name ?></a>
    <? else : ?>
      <span class="<?= $ni->classes ?>"><?= $ni->name ?></span>
    <? endif ?>
    </li><?= str_repeat('</ul></li>', $ni->subDepth); ?>
  <? endif ?>
<? endforeach ?>
</ul>
```

**Comment by jordanlev** [comment]
Hey Ben,
Sorry I wasn't able to respond to this sooner. I'm guessing you are the guy who I wrote that long-winded response to on stackoverflow last week (would be a strange coincidence otherwise!), so hopefully everything has been addressed to your liking.

Feel free to hit me up if you have other questions in the future!

Cheers,
Jordan

**Comment by sciascia** [comment]
Yes thank you Jordan - very helpful. 

Sorry for posting in multiple places - I was trying to solve that issue on the day.

And thanks again for your help - plus all the work you do on c5 for us designers. If you send me a Paypal account username and I’ll buy you a couple of beers!

Cheers

Ben

On 29/04/2014, at 12:14 pm, Jordan Lev notifications@github.com wrote:

> Hey Ben,
> Sorry I wasn't able to respond to this sooner. I'm guessing you are the guy who I wrote that long-winded response to on stackoverflow last week (would be a strange coincidence otherwise!), so hopefully everything has been addressed to your liking.
> 
> Feel free to hit me up if you have other questions in the future!
> 
> Cheers,
> Jordan
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ben Sciascia

Sciascia Brothers
Level 1, 56 Brown Street, Ponsonby
PO Box 68-578 Newton,
Auckland, New Zealand

PH: +649 360 0559
FAX: +649 360 0012
MOB: +64 21 44 33 66

www.sciascia.co.nz

ben.sciascia@sciascia.co.nz

WARNING: This e-mail contains information which is CONFIDENTIAL and may be subject to LEGAL PRIVILEGE. If you are not the intended recipient, you must not peruse, use, disseminate, distribute or copy the e-mail or attachments.  If you have received this message in error, please telephone us immediately and destroy the original message.

---

Ben Sciascia

Sciascia Brothers
Level 1, 56 Brown Street, Ponsonby
PO Box 68-578 Newton,
Auckland, New Zealand

PH: +649 360 0559
FAX: +649 360 0012
MOB: +64 21 44 33 66

www.sciascia.co.nz

ben.sciascia@sciascia.co.nz

WARNING: This e-mail contains information which is CONFIDENTIAL and may be subject to LEGAL PRIVILEGE. If you are not the intended recipient, you must not peruse, use, disseminate, distribute or copy the e-mail or attachments.  If you have received this message in error, please telephone us immediately and destroy the original message.

**Comment by jordanlev** [comment]
No worries, I'm glad you were able to figure something out.
And you're very welcome for the help -- I get a lot out of it as well. No need to send me money (but thanks for the offer) -- perhaps instead just consider if purchasing a license for the Designer Content Pro addon (http://www.concrete5.org/marketplace/addons/designer-content-pro) makes sense for your next project :)

**Comment by sciascia** [comment]
I didn’t know the pro version existed so will definitely use it - the c5 site is down here in NZ so will buy several copies as soon as it’s up.

Cheers

On 29/04/2014, at 12:26 pm, Jordan Lev notifications@github.com wrote:

> No worries, I'm glad you were able to figure something out.
> And you're very welcome for the help -- I get a lot out of it as well. No need to send me money (but thanks for the offer) -- perhaps instead just consider if purchasing a license for the Designer Content Pro addon (http://www.concrete5.org/marketplace/addons/designer-content-pro) makes sense for your next project :)
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ben Sciascia

Sciascia Brothers
Level 1, 56 Brown Street, Ponsonby
PO Box 68-578 Newton,
Auckland, New Zealand

PH: +649 360 0559
FAX: +649 360 0012
MOB: +64 21 44 33 66

www.sciascia.co.nz

ben.sciascia@sciascia.co.nz

WARNING: This e-mail contains information which is CONFIDENTIAL and may be subject to LEGAL PRIVILEGE. If you are not the intended recipient, you must not peruse, use, disseminate, distribute or copy the e-mail or attachments.  If you have received this message in error, please telephone us immediately and destroy the original message.

---

Ben Sciascia

Sciascia Brothers
Level 1, 56 Brown Street, Ponsonby
PO Box 68-578 Newton,
Auckland, New Zealand

PH: +649 360 0559
FAX: +649 360 0012
MOB: +64 21 44 33 66

www.sciascia.co.nz

ben.sciascia@sciascia.co.nz

WARNING: This e-mail contains information which is CONFIDENTIAL and may be subject to LEGAL PRIVILEGE. If you are not the intended recipient, you must not peruse, use, disseminate, distribute or copy the e-mail or attachments.  If you have received this message in error, please telephone us immediately and destroy the original message.

---

Ben Sciascia

Sciascia Brothers
Level 1, 56 Brown Street, Ponsonby
PO Box 68-578 Newton,
Auckland, New Zealand

PH: +649 360 0559
FAX: +649 360 0012
MOB: +64 21 44 33 66

www.sciascia.co.nz

ben.sciascia@sciascia.co.nz

WARNING: This e-mail contains information which is CONFIDENTIAL and may be subject to LEGAL PRIVILEGE. If you are not the intended recipient, you must not peruse, use, disseminate, distribute or copy the e-mail or attachments.  If you have received this message in error, please telephone us immediately and destroy the original message.
